// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMZoS5C1ScyfITuZR-Uicdeq-UROKp3EQ',
    appId: '1:728874770075:web:95396b4a879dc8e9be703e',
    messagingSenderId: '728874770075',
    projectId: 'radishapp-bcfc3',
    authDomain: 'radishapp-bcfc3.firebaseapp.com',
    storageBucket: 'radishapp-bcfc3.appspot.com',
    measurementId: 'G-5DZ05M816W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLAW17mfApL6DZFyC0zNeQ7Urz3tgrhA4',
    appId: '1:728874770075:android:1146480b036610b3be703e',
    messagingSenderId: '728874770075',
    projectId: 'radishapp-bcfc3',
    storageBucket: 'radishapp-bcfc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWrEDaH6I1Ptv02fxpSAnDHf04HbGVTZw',
    appId: '1:728874770075:ios:eb87e2249cd7ef2cbe703e',
    messagingSenderId: '728874770075',
    projectId: 'radishapp-bcfc3',
    storageBucket: 'radishapp-bcfc3.appspot.com',
    iosBundleId: 'com.example.cloneRadishApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWrEDaH6I1Ptv02fxpSAnDHf04HbGVTZw',
    appId: '1:728874770075:ios:eb87e2249cd7ef2cbe703e',
    messagingSenderId: '728874770075',
    projectId: 'radishapp-bcfc3',
    storageBucket: 'radishapp-bcfc3.appspot.com',
    iosBundleId: 'com.example.cloneRadishApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMZoS5C1ScyfITuZR-Uicdeq-UROKp3EQ',
    appId: '1:728874770075:web:3773c390365d2a3fbe703e',
    messagingSenderId: '728874770075',
    projectId: 'radishapp-bcfc3',
    authDomain: 'radishapp-bcfc3.firebaseapp.com',
    storageBucket: 'radishapp-bcfc3.appspot.com',
    measurementId: 'G-BB7C5XJKP0',
  );
}
